-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         11.7.2-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             12.10.0.7000
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para pp3_proyecto
CREATE DATABASE IF NOT EXISTS `pp3_proyecto` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci */;
USE `pp3_proyecto`;

-- Volcando estructura para tabla pp3_proyecto.categorias
CREATE TABLE IF NOT EXISTS `categorias` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  `descripcion` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `nombre` (`nombre`)
) ENGINE=InnoDB AUTO_INCREMENT=462 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Volcando datos para la tabla pp3_proyecto.categorias: ~461 rows (aproximadamente)
INSERT IGNORE INTO `categorias` (`id`, `nombre`, `descripcion`) VALUES
	(1, 'Alimentos Frescos', 'Productos alimenticios que se conservan mejor en refrigeración y tienen una vida útil corta.'),
	(2, 'Alimentos Congelados', 'Productos alimenticios que se conservan mediante congelación para prolongar su vida útil.'),
	(3, 'Alimentos Enlatados', 'Productos alimenticios conservados en latas herméticas para una larga vida útil.'),
	(4, 'Alimentos Horneados', 'Productos alimenticios cocinados al horno, como panes, pasteles y galletas.'),
	(5, 'Bebidas No Alcohólicas', 'Bebidas que no contienen alcohol, como jugos, refrescos y agua.'),
	(6, 'Bebidas Alcohólicas', 'Bebidas que contienen alcohol, como cerveza, vino y licores.'),
	(7, 'Lácteos', 'Productos derivados de la leche, como queso, yogur y mantequilla.'),
	(8, 'Carnes Rojas', 'Carnes de mamíferos, como res, cerdo y cordero.'),
	(9, 'Carnes Blancas', 'Carnes de aves y otros animales, como pollo, pavo y pescado.'),
	(10, 'Embutidos', 'Productos cárnicos procesados, como salchichas, jamón y salami.'),
	(11, 'Frutas', 'Productos vegetales dulces y carnosos, que generalmente contienen semillas.'),
	(12, 'Verduras', 'Productos vegetales comestibles, como hojas, tallos y raíces.'),
	(13, 'Legumbres', 'Semillas comestibles de plantas leguminosas, como frijoles, lentejas y garbanzos.'),
	(14, 'Cereales', 'Granos comestibles de plantas gramíneas, como trigo, arroz y maíz.'),
	(15, 'Granos', 'Semillas comestibles de diversas plantas, incluyendo cereales y pseudocereales como la quinoa.'),
	(16, 'Pastas', 'Productos elaborados con masa de harina, agua y a veces huevos.'),
	(17, 'Salsas', 'Líquidos o semilíquidos que acompañan a otros alimentos para darles sabor.'),
	(18, 'Especias', 'Sustancias aromáticas utilizadas para sazonar alimentos.'),
	(19, 'Aceites', 'Lípidos líquidos a temperatura ambiente, utilizados en la cocina.'),
	(20, 'Vinagres', 'Líquidos ácidos utilizados para sazonar y conservar alimentos.'),
	(21, 'Snacks Dulces', 'Alimentos procesados dulces que se consumen entre comidas.'),
	(22, 'Snacks Salados', 'Alimentos procesados salados que se consumen entre comidas.'),
	(23, 'Dulces', 'Alimentos con alto contenido de azúcar.'),
	(24, 'Postres', 'Platos dulces que se sirven al final de una comida.'),
	(25, 'Helados', 'Postres congelados a base de leche u otros ingredientes.'),
	(26, 'Café', 'Bebida elaborada con granos de café tostados.'),
	(27, 'Té', 'Bebida elaborada con hojas de la planta del té.'),
	(28, 'Hierbas', 'Plantas aromáticas utilizadas para dar sabor a los alimentos.'),
	(29, 'Alimentos Dietéticos', 'Alimentos diseñados para satisfacer necesidades dietéticas específicas.'),
	(30, 'Alimentos Orgánicos', 'Alimentos producidos sin el uso de pesticidas sintéticos ni fertilizantes.'),
	(31, 'Muebles de Sala', 'Muebles diseñados para la sala de estar o salón.'),
	(32, 'Muebles de Comedor', 'Muebles diseñados para el comedor.'),
	(33, 'Muebles de Dormitorio', 'Muebles diseñados para el dormitorio.'),
	(34, 'Muebles de Oficina', 'Muebles diseñados para espacios de trabajo.'),
	(35, 'Muebles de Exterior', 'Muebles diseñados para uso en exteriores.'),
	(36, 'Muebles de Baño', 'Muebles diseñados para el baño.'),
	(37, 'Muebles de Cocina', 'Muebles diseñados para la cocina.'),
	(38, 'Muebles de Recibidor', 'Muebles diseñados para la entrada o recibidor.'),
	(39, 'Muebles Infantiles', 'Muebles diseñados para niños.'),
	(40, 'Muebles Juveniles', 'Muebles diseñados para adolescentes.'),
	(41, 'Sofás', 'Asientos largos con respaldo y brazos.'),
	(42, 'Sillones', 'Asientos individuales con respaldo y brazos.'),
	(43, 'Mesas de Centro', 'Mesas bajas ubicadas en el centro de la sala.'),
	(44, 'Mesas Laterales', 'Mesas pequeñas ubicadas al lado de sofás o sillones.'),
	(45, 'Estanterías', 'Muebles con estantes para almacenar objetos.'),
	(46, 'Libreros', 'Estanterías diseñadas para almacenar libros.'),
	(47, 'Vitrinas', 'Muebles con puertas de vidrio para exhibir objetos.'),
	(48, 'Aparadores', 'Muebles bajos con cajones y puertas para almacenar objetos.'),
	(49, 'Muebles de TV', 'Muebles diseñados para sostener televisores y equipos de entretenimiento.'),
	(50, 'Chimeneas Eléctricas', 'Dispositivos de calefacción que simulan una chimenea.'),
	(51, 'Mesas de Comedor', 'Mesas grandes diseñadas para comer.'),
	(52, 'Sillas de Comedor', 'Asientos diseñados para acompañar mesas de comedor.'),
	(53, 'Bancos de Comedor', 'Asientos largos sin respaldo diseñados para el comedor.'),
	(54, 'Alacenas', 'Muebles de cocina para almacenar utensilios y alimentos.'),
	(55, 'Bajomesadas', 'Muebles de cocina ubicados debajo de la encimera.'),
	(56, 'Islas de Cocina', 'Muebles de cocina independientes ubicados en el centro de la cocina.'),
	(57, 'Camas Matrimoniales', 'Camas diseñadas para dos personas.'),
	(58, 'Camas Individuales', 'Camas diseñadas para una persona.'),
	(59, 'Camas Nido', 'Camas que incluyen una cama adicional que se guarda debajo.'),
	(60, 'Camas Cuchetas', 'Camas apiladas una encima de la otra.'),
	(61, 'Cabeceros de Cama', 'Paneles decorativos ubicados en la cabecera de la cama.'),
	(62, 'Mesas de Noche', 'Mesas pequeñas ubicadas al lado de la cama.'),
	(63, 'Cómodas', 'Muebles con cajones para almacenar ropa.'),
	(64, 'Armarios', 'Muebles grandes para almacenar ropa.'),
	(65, 'Tocadores', 'Muebles con espejo y cajones para maquillarse y arreglarse.'),
	(66, 'Escritorios', 'Mesas diseñadas para trabajar o estudiar.'),
	(67, 'Sillas de Escritorio', 'Asientos diseñados para acompañar escritorios.'),
	(68, 'Estanterías de Oficina', 'Estanterías diseñadas para almacenar documentos y libros en oficinas.'),
	(69, 'Archivadores', 'Muebles con cajones diseñados para almacenar documentos.'),
	(70, 'Mesas de Reuniones', 'Mesas grandes diseñadas para reuniones de trabajo.'),
	(71, 'Sofás de Exterior', 'Sofás diseñados para uso en exteriores.'),
	(72, 'Sillas de Exterior', 'Sillas diseñadas para uso en exteriores.'),
	(73, 'Mesas de Exterior', 'Mesas diseñadas para uso en exteriores.'),
	(74, 'Tumbonas', 'Sillas largas y reclinables para tomar el sol.'),
	(75, 'Hamacas', 'Colgantes de tela o red para descansar.'),
	(76, 'Juegos de Jardín', 'Conjuntos de muebles diseñados para jardines.'),
	(77, 'Muebles de Baño Auxiliares', 'Muebles pequeños adicionales para el baño.'),
	(78, 'Espejos de Baño', 'Espejos diseñados para el baño.'),
	(79, 'Muebles de Cocina Modulares', 'Muebles de cocina que se pueden combinar y adaptar.'),
	(80, 'Barras de Cocina', 'Mesas altas diseñadas para comer o beber en la cocina.'),
	(81, 'Percheros', 'Muebles para colgar ropa.'),
	(82, 'Consolas de Recibidor', 'Mesas estrechas ubicadas en la entrada.'),
	(83, 'Zapateros', 'Muebles para almacenar zapatos.'),
	(84, 'Baúles', 'Cajas grandes con tapa para almacenar objetos.'),
	(85, 'Camas Elásticas', 'Estructuras con una superficie elástica para saltar.'),
	(86, 'Cunas', 'Camas pequeñas para bebés.'),
	(87, 'Cambiadores', 'Mesas diseñadas para cambiar pañales a bebés.'),
	(88, 'Sillas de Comer para Bebés', 'Sillas altas diseñadas para que los bebés coman.'),
	(89, 'Camas Altas', 'Camas elevadas del suelo.'),
	(90, 'Somieres de Láminas', 'Bases de cama formadas por láminas de madera.'),
	(91, 'Somieres de Resortes', 'Bases de cama formadas por resortes.'),
	(92, 'Somieres Tapizados', 'Bases de cama cubiertas de tela.'),
	(93, 'Somieres Articulados', 'Bases de cama que se pueden ajustar en diferentes posiciones.'),
	(94, 'Somieres con Cajones', 'Bases de cama que incluyen cajones para almacenamiento.'),
	(95, 'Somieres Diván', 'Bases de cama que se pueden usar como sofá.'),
	(96, 'Computadoras de Escritorio', 'Computadoras diseñadas para uso en un lugar fijo.'),
	(97, 'Computadoras Portátiles', 'Computadoras que se pueden transportar fácilmente.'),
	(98, 'Computadoras All in One', 'Computadoras que integran todos los componentes en el monitor.'),
	(99, 'Mini PC', 'Computadoras pequeñas y compactas.'),
	(100, 'Servidores', 'Computadoras diseñadas para proporcionar servicios a otras computadoras.'),
	(101, 'Componentes de PC', 'Partes que conforman una computadora.'),
	(102, 'Monitores', 'Pantallas para mostrar la información de la computadora.'),
	(103, 'Impresoras', 'Dispositivos para imprimir documentos.'),
	(104, 'Scanners', 'Dispositivos para digitalizar documentos.'),
	(105, 'Periféricos', 'Dispositivos que se conectan a la computadora, como teclados y ratones.'),
	(106, 'Accesorios de Computación', 'Artículos que complementan el uso de la computadora.'),
	(107, 'Software', 'Programas que permiten a la computadora realizar tareas.'),
	(108, 'Redes y Conectividad', 'Tecnologías que permiten la comunicación entre computadoras.'),
	(109, 'Almacenamiento', 'Dispositivos para guardar información, como discos duros y unidades SSD.'),
	(110, 'Audio y Video', 'Componentes y dispositivos relacionados con el sonido y la imagen.'),
	(111, 'Panes Integrales', 'Panes elaborados con harina integral.'),
	(112, 'Quesos de Cabra', 'Quesos elaborados con leche de cabra.'),
	(113, 'Chocolates Orgánicos', 'Chocolates elaborados con ingredientes orgánicos.'),
	(114, 'Cortes de Carne Angus', 'Cortes de carne de la raza Angus.'),
	(115, 'Cervezas Stout', 'Cervezas oscuras y fuertes.'),
	(116, 'Mermeladas Caseras', 'Mermeladas elaboradas de forma artesanal.'),
	(117, 'Frutos Secos Tostados', 'Frutos secos cocinados al horno.'),
	(118, 'Tés de Hierbas', 'Tés elaborados con hierbas en lugar de hojas de té.'),
	(119, 'Aceites de Oliva Virgen Extra', 'Aceites de oliva de alta calidad.'),
	(120, 'Vinagres Balsámicos', 'Vinagres oscuros y dulces.'),
	(121, 'Mesas de Comedor Extensibles', 'Mesas de comedor que se pueden alargar.'),
	(122, 'Sillas de Comedor Tapizadas', 'Sillas de comedor con asiento y respaldo cubiertos de tela.'),
	(123, 'Sofás Cama', 'Sofás que se pueden convertir en cama.'),
	(124, 'Sillones Reclinables', 'Sillones cuyo respaldo se puede inclinar.'),
	(125, 'Estanterías Modulares', 'Estanterías que se pueden montar y combinar de diferentes maneras.'),
	(126, 'Camas con Almacenamiento', 'Camas que incluyen espacio para guardar objetos.'),
	(127, 'Somieres con Cajones Laterales', 'Somieres con cajones ubicados a los lados.'),
	(128, 'Notebooks Ultrabook', 'Computadoras portátiles delgadas y ligeras.'),
	(129, 'Placas Base ATX', 'Placas base de tamaño estándar para computadoras de escritorio.'),
	(130, 'Monitores Curvos', 'Monitores con pantalla curva.'),
	(131, 'Impresoras Multifunción', 'Impresoras que también pueden escanear y copiar.'),
	(132, 'Teclados Mecánicos', 'Teclados con interruptores mecánicos individuales para cada tecla.'),
	(133, 'Auriculares Gaming', 'Auriculares diseñados para videojuegos.'),
	(134, 'Discos Sólidos SSD', 'Dispositivos de almacenamiento de datos que utilizan memoria flash.'),
	(135, 'Routers Inalámbricos', 'Dispositivos que permiten la conexión a internet sin cables.'),
	(136, 'Tarjetas Gráficas NVIDIA', 'Tarjetas gráficas fabricadas por NVIDIA.'),
	(137, 'Procesadores Intel Core i9', 'Procesadores de alta gama fabricados por Intel.'),
	(138, 'Memorias RAM DDR5', 'Módulos de memoria RAM de quinta generación.'),
	(139, 'Fuentes de Alimentación 80 Plus Gold', 'Fuentes de alimentación con certificación de eficiencia energética.'),
	(140, 'Cajas de PC con Ventilación Avanzada', 'Cajas de computadora diseñadas para una buena circulación del aire.'),
	(141, 'Sistemas de Refrigeración Líquida para PC', 'Sistemas que utilizan líquido para enfriar los componentes de la computadora.'),
	(142, 'Pastas sin Gluten', 'Pastas elaboradas sin gluten.'),
	(143, 'Productos Kosher', 'Productos que cumplen con las leyes dietéticas judías.'),
	(144, 'Alimentos Halal', 'Alimentos que cumplen con las leyes dietéticas islámicas.'),
	(145, 'Suplementos Deportivos', 'Productos diseñados para mejorar el rendimiento deportivo.'),
	(146, 'Bebidas Energéticas', 'Bebidas diseñadas para aumentar la energía.'),
	(147, 'Jugos Naturales', 'Jugos elaborados con frutas y verduras frescas.'),
	(148, 'Aguas Saborizadas', 'Aguas con saborizantes añadidos.'),
	(149, 'Tés Fríos', 'Tés que se sirven fríos.'),
	(150, 'Infusiones Funcionales', 'Infusiones con beneficios para la salud.'),
	(151, 'Muebles de Estilo Clásico', 'Muebles que imitan estilos antiguos.'),
	(152, 'Muebles de Estilo Moderno', 'Muebles con diseños contemporáneos.'),
	(153, 'Muebles de Estilo Rústico', 'Muebles que evocan la vida en el campo.'),
	(154, 'Muebles de Estilo Vintage', 'Muebles que imitan estilos de décadas pasadas.'),
	(155, 'Muebles de Estilo Industrial', 'Muebles que incorporan elementos de fábricas y almacenes.'),
	(156, 'Camas con Dosel', 'Camas con una estructura superior que sostiene cortinas.'),
	(157, 'Somieres con Masaje', 'Somieres que incorporan motores de masaje.'),
	(158, 'Computadoras All in One Touch Screen', 'Computadoras All in One con pantalla táctil.'),
	(159, 'Mini PC para Señalización Digital', 'Mini PCs diseñadas para mostrar contenido en pantallas.'),
	(160, 'Servidores Blade', 'Servidores compactos que se insertan en un chasis.'),
	(161, 'Panes de Masa Madre', 'Panes elaborados con masa madre.'),
	(162, 'Quesos Veganos', 'Quesos elaborados sin productos de origen animal.'),
	(163, 'Chocolates Sin Azúcar', 'Chocolates elaborados sin azúcar añadida.'),
	(164, 'Cortes de Carne Orgánica', 'Cortes de carne de animales criados de forma orgánica.'),
	(165, 'Cervezas Artesanales de Trigo', 'Cervezas elaboradas con trigo.'),
	(166, 'Mermeladas Sin Azúcar', 'Mermeladas elaboradas sin azúcar añadida.'),
	(167, 'Frutos Secos Orgánicos', 'Frutos secos cultivados sin pesticidas ni fertilizantes sintéticos.'),
	(168, 'Tés de Frutas', 'Tés elaborados con trozos de frutas.'),
	(169, 'Aceites de Coco', 'Aceites elaborados con coco.'),
	(170, 'Vinagres de Manzana', 'Vinagres elaborados con sidra de manzana.'),
	(171, 'Mesas de Comedor Redondas', 'Mesas de comedor con forma circular.'),
	(172, 'Sillas de Comedor de Diseño', 'Sillas de comedor con diseños originales.'),
	(173, 'Sofás Modulares', 'Sofás que se pueden configurar de diferentes maneras.'),
	(174, 'Sillones Masajeadores', 'Sillones que incorporan motores de masaje.'),
	(175, 'Estanterías Flotantes', 'Estanterías que se fijan a la pared sin soportes visibles.'),
	(176, 'Camas con Cabecero Acolchado', 'Camas con un cabecero cubierto de tela acolchada.'),
	(177, 'Somieres con Sistema de Elevación Eléctrico', 'Somieres que se pueden elevar y bajar eléctricamente.'),
	(178, 'Notebooks 2 en 1', 'Computadoras portátiles que se pueden usar como tabletas.'),
	(179, 'Placas Base Micro ATX', 'Placas base de tamaño reducido para computadoras de escritorio.'),
	(180, 'Monitores Ultrawide', 'Monitores con una relación de aspecto ultra ancha.'),
	(181, 'Impresoras Láser Color', 'Impresoras que utilizan tecnología láser para imprimir en color.'),
	(182, 'Teclados Inalámbricos Ergonómicos', 'Teclados diseñados para reducir la tensión en las manos y las muñecas.'),
	(183, 'Auriculares Inalámbricos con Cancelación de Ruido', 'Auriculares que eliminan el ruido ambiental.'),
	(184, 'Discos Duros Externos SSD', 'Dispositivos de almacenamiento de datos externos que utilizan memoria flash.'),
	(185, 'Routers Mesh', 'Sistemas de routers que proporcionan una cobertura de red amplia y estable.'),
	(186, 'Tarjetas Gráficas AMD Radeon RX', 'Tarjetas gráficas fabricadas por AMD.'),
	(187, 'Procesadores AMD Ryzen Threadripper', 'Procesadores de alta gama fabricados por AMD.'),
	(188, 'Memorias RAM ECC', 'Módulos de memoria RAM que detectan y corrigen errores.'),
	(189, 'Fuentes de Alimentación 80 Plus Titanium', 'Fuentes de alimentación con la máxima certificación de eficiencia energética.'),
	(190, 'Cajas de PC con Iluminación RGB Personalizable', 'Cajas de computadora con luces LED que se pueden personalizar.'),
	(191, 'Sistemas de Refrigeración Líquida AIO para PC', 'Sistemas de refrigeración líquida todo en uno para computadoras.'),
	(192, 'Alimentos para Bebés', 'Alimentos diseñados para bebés.'),
	(193, 'Alimentos para Mascotas', 'Alimentos diseñados para animales domésticos.'),
	(194, 'Alimentos Funcionales', 'Alimentos que proporcionan beneficios para la salud más allá de la nutrición básica.'),
	(195, 'Alimentos Enriquecidos', 'Alimentos a los que se les han añadido nutrientes.'),
	(196, 'Alimentos Fortificados', 'Alimentos a los que se les han añadido nutrientes en mayor cantidad que en los enriquecidos.'),
	(197, 'Alimentos Probióticos', 'Alimentos que contienen microorganismos vivos que son beneficiosos para la salud.'),
	(198, 'Alimentos Prebióticos', 'Alimentos que contienen ingredientes no digeribles que estimulan el crecimiento de microorganismos beneficiosos en el intestino.'),
	(199, 'Alimentos Simbióticos', 'Alimentos que combinan probióticos y prebióticos.'),
	(200, 'Alimentos Transgénicos', 'Alimentos que han sido modificados genéticamente.'),
	(201, 'Alimentos Ecológicos', 'Sinónimo de alimentos orgánicos.'),
	(202, 'Alimentos Biológicos', 'Sinónimo de alimentos orgánicos.'),
	(203, 'Alimentos Biodinámicos', 'Alimentos producidos siguiendo los principios de la agricultura biodinámica.'),
	(204, 'Alimentos de Comercio Justo', 'Alimentos producidos y comercializados de manera ética.'),
	(205, 'Alimentos de Temporada', 'Alimentos que se consumen en la época del año en que son naturalmente abundantes.'),
	(206, 'Alimentos de Proximidad', 'Alimentos producidos cerca del lugar donde se consumen.'),
	(207, 'Alimentos Artesanales', 'Alimentos elaborados de forma tradicional y en pequeñas cantidades.'),
	(208, 'Alimentos Gourmet', 'Alimentos de alta calidad y elaborados con ingredientes selectos.'),
	(209, 'Alimentos Étnicos', 'Alimentos originarios de diferentes culturas.'),
	(210, 'Alimentos Regionales', 'Alimentos típicos de una región geográfica específica.'),
	(211, 'Muebles de Madera Maciza', 'Muebles elaborados con piezas sólidas de madera.'),
	(212, 'Muebles de Melamina', 'Muebles recubiertos con láminas de melamina.'),
	(213, 'Muebles de Aglomerado', 'Muebles elaborados con partículas de madera prensadas con resina.'),
	(214, 'Muebles de MDF', 'Muebles elaborados con fibras de madera prensadas con resina.'),
	(215, 'Muebles de Metal', 'Muebles elaborados principalmente con metal.'),
	(216, 'Muebles de Cristal', 'Muebles que incorporan elementos de cristal o vidrio.'),
	(217, 'Muebles de Piel', 'Muebles tapizados en piel.'),
	(218, 'Muebles de Tela', 'Muebles tapizados en tela.'),
	(219, 'Muebles de Ratán', 'Muebles elaborados con fibras de ratán.'),
	(220, 'Muebles de Bambú', 'Muebles elaborados con bambú.'),
	(221, 'Muebles de Estilo Luis XV', 'Muebles que imitan el estilo francés del siglo XVIII.'),
	(222, 'Muebles de Estilo Imperio', 'Muebles que imitan el estilo francés del siglo XIX.'),
	(223, 'Muebles de Estilo Art Decó', 'Muebles con diseños geométricos y lujosos de la década de 1920.'),
	(224, 'Muebles de Estilo Bauhaus', 'Muebles con diseños funcionales y minimalistas de la escuela Bauhaus.'),
	(225, 'Muebles de Estilo Mid-Century Modern', 'Muebles con diseños elegantes y sencillos de mediados del siglo XX.'),
	(226, 'Camas con Cabecero de Madera', 'Camas con un cabecero elaborado en madera.'),
	(227, 'Camas con Cabecero Tapizado', 'Camas con un cabecero cubierto de tela.'),
	(228, 'Camas con Cabecero de Hierro Forjado', 'Camas con un cabecero elaborado en hierro.'),
	(229, 'Camas con Cabecero Flotante', 'Camas con un cabecero que parece estar suspendido en la pared.'),
	(230, 'Camas con Cabecero Abatible', 'Camas con un cabecero que se puede inclinar hacia adelante.'),
	(231, 'Somieres con Sistema de Regulación de Firmeza', 'Somieres que permiten ajustar la firmeza de la superficie de descanso.'),
	(232, 'Somieres con Sistema de Zona de Descanso', 'Somieres que ofrecen diferentes niveles de firmeza en distintas zonas.'),
	(233, 'Somieres con Sistema Antirruido', 'Somieres diseñados para minimizar los ruidos durante el movimiento.'),
	(234, 'Somieres con Sistema de Ventilación', 'Somieres que permiten una mejor circulación del aire.'),
	(235, 'Somieres con Sistema de Masaje Vibratorio', 'Somieres que incorporan vibradores para proporcionar masaje.'),
	(236, 'Computadoras de Escritorio Gaming', 'Computadoras de escritorio diseñadas para videojuegos.'),
	(237, 'Computadoras de Escritorio para Diseño', 'Computadoras de escritorio diseñadas para diseño gráfico.'),
	(238, 'Computadoras de Escritorio para Edición de Video', 'Computadoras de escritorio diseñadas para edición de video.'),
	(239, 'Computadoras de Escritorio para Ofimática', 'Computadoras de escritorio diseñadas para tareas de oficina.'),
	(240, 'Computadoras de Escritorio Todo en Uno', 'Computadoras de escritorio que integran todos los componentes en el monitor.'),
	(241, 'Notebooks Ultraligeras', 'Computadoras portátiles muy ligeras.'),
	(242, 'Notebooks Convertibles', 'Computadoras portátiles que se pueden usar como tabletas.'),
	(243, 'Notebooks para Estudiantes', 'Computadoras portátiles diseñadas para estudiantes.'),
	(244, 'Notebooks para Empresas', 'Computadoras portátiles diseñadas para uso profesional.'),
	(245, 'Notebooks con Pantalla Táctil', 'Computadoras portátiles con pantalla que se puede tocar.'),
	(246, 'Monitores para Diseño Gráfico', 'Monitores con alta precisión de color.'),
	(247, 'Monitores para Gaming', 'Monitores con alta frecuencia de actualización y bajo tiempo de respuesta.'),
	(248, 'Monitores para Oficina', 'Monitores con buena ergonomía y comodidad visual.'),
	(249, 'Monitores Curvos Ultrawide', 'Monitores curvos con una relación de aspecto ultra ancha.'),
	(250, 'Monitores 4K', 'Monitores con resolución 4K.'),
	(251, 'Impresoras 3D', 'Dispositivos que crean objetos tridimensionales a partir de un diseño digital.'),
	(252, 'Impresoras de Etiquetas', 'Dispositivos que imprimen etiquetas adhesivas.'),
	(253, 'Impresoras Fotográficas', 'Dispositivos que imprimen fotografías de alta calidad.'),
	(254, 'Impresoras de Gran Formato', 'Dispositivos que imprimen en tamaños de papel grandes.'),
	(255, 'Impresoras de Sublimación', 'Dispositivos que transfieren diseños a objetos mediante calor.'),
	(256, 'Scanners de Documentos', 'Dispositivos que digitalizan documentos en papel.'),
	(257, 'Scanners de Negativos', 'Dispositivos que digitalizan negativos fotográficos.'),
	(258, 'Scanners 3D', 'Dispositivos que digitalizan objetos tridimensionales.'),
	(259, 'Scanners de Códigos de Barras', 'Dispositivos que leen códigos de barras.'),
	(260, 'Scanners de Tarjetas de Crédito', 'Dispositivos que leen la información de las tarjetas de crédito.'),
	(261, 'Teclados Inalámbricos con Touchpad', 'Teclados que incorporan una superficie táctil.'),
	(262, 'Teclados Ergonómicos Divididos', 'Teclados que se dividen en dos partes para reducir la tensión en las muñecas.'),
	(263, 'Teclados para Gaming Mecánicos', 'Teclados mecánicos diseñados para videojuegos.'),
	(264, 'Teclados con Iluminación RGB', 'Teclados con luces LED que se pueden personalizar.'),
	(265, 'Teclados con Lector de Huellas Digitales', 'Teclados que permiten iniciar sesión con la huella digital.'),
	(266, 'Ratones Inalámbricos Ergonómicos', 'Ratones diseñados para reducir la tensión en la mano y la muñeca.'),
	(267, 'Ratones para Gaming con Pesas Ajustables', 'Ratones que permiten ajustar el peso para adaptarse a las preferencias del usuario.'),
	(268, 'Ratones con Sensor Láser', 'Ratones que utilizan tecnología láser para un seguimiento preciso.'),
	(269, 'Ratones con Botones Programables', 'Ratones que permiten asignar funciones a los botones.'),
	(270, 'Ratones con Scroll Vertical y Horizontal', 'Ratones que permiten desplazarse por las páginas tanto vertical como horizontalmente.'),
	(271, 'Altavoces Estéreo', 'Conjunto de dos altavoces para reproducir sonido estéreo.'),
	(272, 'Altavoces 2.1', 'Conjunto de dos altavoces y un subwoofer.'),
	(273, 'Altavoces 5.1', 'Conjunto de cinco altavoces y un subwoofer para sonido envolvente.'),
	(274, 'Altavoces Bluetooth Portátiles', 'Altavoces pequeños que se pueden transportar y conectar de forma inalámbrica.'),
	(275, 'Barras de Sonido', 'Altavoces largos y delgados diseñados para mejorar el sonido de los televisores.'),
	(276, 'Auriculares Inalámbricos Over-Ear', 'Auriculares que cubren completamente las orejas.'),
	(277, 'Auriculares Inalámbricos On-Ear', 'Auriculares que se apoyan en las orejas.'),
	(278, 'Auriculares Inalámbricos In-Ear', 'Auriculares que se insertan en el canal auditivo.'),
	(279, 'Micrófonos USB', 'Micrófonos que se conectan a la computadora a través de USB.'),
	(280, 'Webcams', 'Cámaras web para videollamadas y transmisiones en vivo.'),
	(281, 'Sistemas Operativos', 'Software que controla el hardware de la computadora.'),
	(282, 'Software de Ofimática', 'Programas para crear documentos, hojas de cálculo y presentaciones.'),
	(283, 'Software de Diseño Gráfico', 'Programas para crear y editar imágenes y gráficos.'),
	(284, 'Software de Edición de Video', 'Programas para editar y producir videos.'),
	(285, 'Software de Edición de Audio', 'Programas para grabar y editar audio.'),
	(286, 'Software de Seguridad', 'Programas para proteger la computadora de virus y otras amenazas.'),
	(287, 'Software de Desarrollo', 'Programas para crear otros programas.'),
	(288, 'Software de Base de Datos', 'Programas para gestionar y organizar información.'),
	(289, 'Software de Redes', 'Programas para configurar y gestionar redes de computadoras.'),
	(290, 'Software de Juegos', 'Videojuegos para computadora.'),
	(291, 'Cables de Red Ethernet', 'Cables para conectar computadoras en una red local.'),
	(292, 'Cables HDMI', 'Cables para transmitir audio y video digital de alta definición.'),
	(293, 'Cables USB', 'Cables para conectar dispositivos a la computadora.'),
	(294, 'Adaptadores de Red Inalámbricos USB', 'Dispositivos que permiten conectar una computadora a una red Wi-Fi.'),
	(295, 'Switches de Red', 'Dispositivos que conectan varios dispositivos en una red local.'),
	(296, 'Routers', 'Dispositivos que conectan una red local a internet.'),
	(297, 'Tarjetas de Red', 'Componentes que permiten a una computadora comunicarse con otras en una red.'),
	(298, 'Puntos de Acceso Wi-Fi', 'Dispositivos que crean una red Wi-Fi.'),
	(299, 'Modems', 'Dispositivos que permiten la conexión a internet a través de líneas telefónicas o de cable.'),
	(300, 'Antenas Wi-Fi', 'Dispositivos que mejoran la señal de la red Wi-Fi.'),
	(301, 'Discos Duros Internos HDD', 'Dispositivos de almacenamiento de datos que utilizan platos magnéticos.'),
	(302, 'Discos Duros Externos HDD', 'Dispositivos de almacenamiento de datos externos que utilizan platos magnéticos.'),
	(303, 'Unidades SSD Internas', 'Dispositivos de almacenamiento de datos internos que utilizan memoria flash.'),
	(304, 'Unidades SSD Externas', 'Dispositivos de almacenamiento de datos externos que utilizan memoria flash.'),
	(305, 'Tarjetas de Memoria SD', 'Dispositivos de almacenamiento de datos portátiles.'),
	(306, 'Unidades Flash USB', 'Dispositivos de almacenamiento de datos portátiles que se conectan a través de USB.'),
	(307, 'Lectoras de Tarjetas de Memoria', 'Dispositivos que permiten leer y escribir en tarjetas de memoria.'),
	(308, 'Grabadoras de CD/DVD', 'Dispositivos que permiten grabar datos en CD y DVD.'),
	(309, 'Unidades de Cinta Magnética', 'Dispositivos de almacenamiento de datos de gran capacidad utilizados para copias de seguridad.'),
	(310, 'Sistemas NAS', 'Dispositivos de almacenamiento en red.'),
	(311, 'Tarjetas de Sonido Internas', 'Componentes que permiten a la computadora reproducir y grabar sonido.'),
	(312, 'Tarjetas de Sonido Externas', 'Dispositivos que permiten a la computadora reproducir y grabar sonido y se conectan a través de USB.'),
	(313, 'Tarjetas de Video Internas', 'Componentes que permiten a la computadora mostrar imágenes en la pantalla.'),
	(314, 'Tarjetas de Video Externas', 'Dispositivos que permiten a la computadora mostrar imágenes en la pantalla y se conectan a través de USB o Thunderbolt.'),
	(315, 'Capturadoras de Video', 'Dispositivos que permiten grabar video de fuentes externas.'),
	(316, 'Sintonizadoras de TV', 'Dispositivos que permiten ver televisión en la computadora.'),
	(317, 'Reproductores de DVD/Blu-ray', 'Dispositivos que permiten reproducir DVD y Blu-ray en la computadora.'),
	(318, 'Proyectores', 'Dispositivos que proyectan imágenes en una superficie.'),
	(319, 'Pantallas de Proyección', 'Superficies diseñadas para mostrar imágenes proyectadas.'),
	(320, 'Gafas de Realidad Virtual', 'Dispositivos que sumergen al usuario en un entorno virtual.'),
	(321, 'Gafas de Realidad Aumentada', 'Dispositivos que superponen información digital al mundo real.'),
	(322, 'Mandos de Juegos', 'Dispositivos que se utilizan para controlar videojuegos.'),
	(323, 'Volantes de Carreras', 'Dispositivos que simulan la experiencia de conducir un automóvil de carreras.'),
	(324, 'Joysticks', 'Dispositivos que se utilizan para controlar aviones y otros vehículos en videojuegos.'),
	(325, 'Alfombrillas de Ratón para Gaming', 'Superficies diseñadas para un movimiento preciso del ratón.'),
	(326, 'Sillas de Gaming Ergonómicas', 'Sillas diseñadas para proporcionar comodidad durante largas sesiones de juego.'),
	(327, 'Mesas de Gaming', 'Mesas diseñadas para acomodar equipos de juego.'),
	(328, 'Panes de Centeno', 'Panes elaborados con harina de centeno.'),
	(329, 'Quesos Azules', 'Quesos con vetas de moho azul.'),
	(330, 'Chocolates con Frutos Secos', 'Chocolates que contienen frutos secos.'),
	(331, 'Cortes de Carne Madurada', 'Cortes de carne que han sido envejecidos para mejorar su sabor y textura.'),
	(332, 'Cervezas Pale Ale', 'Cervezas de color claro y sabor amargo.'),
	(333, 'Mermeladas de Frutas Exóticas', 'Mermeladas elaboradas con frutas poco comunes.'),
	(334, 'Frutos Secos Caramelizados', 'Frutos secos cubiertos de caramelo.'),
	(335, 'Tés de Flores', 'Tés elaborados con flores.'),
	(336, 'Aceites Infusionados', 'Aceites a los que se les han añadido hierbas o especias.'),
	(337, 'Vinagres de Frutas', 'Vinagres elaborados con frutas.'),
	(338, 'Mesas de Centro Elevables', 'Mesas de centro que se pueden elevar para comer o trabajar.'),
	(339, 'Sillas de Comedor con Brazos', 'Sillas de comedor que incluyen brazos.'),
	(340, 'Sofás Chaiselongue', 'Sofás con una sección alargada para estirar las piernas.'),
	(341, 'Sillones Orejeros', 'Sillones altos con paneles laterales que protegen del frío.'),
	(342, 'Estanterías con Puertas', 'Estanterías que incluyen puertas para ocultar objetos.'),
	(343, 'Camas con Canapé', 'Camas que incluyen un espacio de almacenamiento debajo del colchón.'),
	(344, 'Somieres con Sistema de Regulación Lumbar', 'Somieres que permiten ajustar la firmeza en la zona lumbar.'),
	(345, 'Notebooks con Pantalla OLED', 'Computadoras portátiles con pantallas que ofrecen colores vivos y negros profundos.'),
	(346, 'Placas Base Mini ITX', 'Placas base de tamaño muy reducido para computadoras de escritorio.'),
	(347, 'Monitores con Tecnología G-Sync', 'Monitores que sincronizan la frecuencia de actualización con la tarjeta gráfica.'),
	(348, 'Impresoras de Inyección de Tinta', 'Impresoras que utilizan tinta líquida para imprimir.'),
	(349, 'Teclados Inalámbricos con Retroiluminación', 'Teclados que se iluminan para facilitar la escritura en la oscuridad.'),
	(350, 'Auriculares Inalámbricos para Deportes', 'Auriculares diseñados para actividades físicas.'),
	(351, 'Discos Duros Externos Portátiles', 'Dispositivos de almacenamiento de datos externos que son fáciles de transportar.'),
	(352, 'Routers con Tecnología Wi-Fi 6', 'Routers que utilizan el último estándar de Wi-Fi.'),
	(353, 'Tarjetas Gráficas NVIDIA GeForce RTX', 'Tarjetas gráficas de última generación fabricadas por NVIDIA.'),
	(354, 'Procesadores Intel Core i7', 'Procesadores de gama media-alta fabricados por Intel.'),
	(355, 'Memorias RAM DDR4', 'Módulos de memoria RAM de cuarta generación.'),
	(356, 'Fuentes de Alimentación Modulares', 'Fuentes de alimentación que permiten conectar solo los cables necesarios.'),
	(357, 'Cajas de PC con Panel Lateral de Cristal Templado', 'Cajas de computadora que permiten ver los componentes internos.'),
	(358, 'Sistemas de Refrigeración Líquida Personalizados para PC', 'Sistemas de refrigeración líquida que se pueden configurar según las necesidades del usuario.'),
	(359, 'Alimentos para Aves', 'Alimentos diseñados para pájaros.'),
	(360, 'Alimentos para Peces', 'Alimentos diseñados para peces.'),
	(361, 'Alimentos para Roedores', 'Alimentos diseñados para ratones, hámsteres y otros roedores.'),
	(362, 'Alimentos para Reptiles', 'Alimentos diseñados para serpientes, lagartos y otros reptiles.'),
	(363, 'Alimentos para Anfibios', 'Alimentos diseñados para ranas, sapos y otros anfibios.'),
	(364, 'Alimentos Hipoalergénicos', 'Alimentos diseñados para personas con alergias.'),
	(365, 'Alimentos Sin Lactosa', 'Alimentos que no contienen lactosa.'),
	(366, 'Alimentos Sin Huevo', 'Alimentos que no contienen huevo.'),
	(367, 'Alimentos Sin Soja', 'Alimentos que no contienen soja.'),
	(368, 'Alimentos Sin Nueces', 'Alimentos que no contienen nueces.'),
	(369, 'Alimentos Sin Cacahuete', 'Alimentos que no contienen cacahuete.'),
	(370, 'Alimentos Bajos en Sodio', 'Alimentos que contienen poca sal.'),
	(371, 'Alimentos Bajos en Grasa', 'Alimentos que contienen poca grasa.'),
	(372, 'Alimentos Bajos en Azúcar', 'Alimentos que contienen poco azúcar.'),
	(373, 'Alimentos Altos en Fibra', 'Alimentos que contienen mucha fibra.'),
	(374, 'Alimentos Altos en Proteína', 'Alimentos que contienen mucha proteína.'),
	(375, 'Alimentos Altos en Vitaminas', 'Alimentos que contienen muchas vitaminas.'),
	(376, 'Alimentos Altos en Minerales', 'Alimentos que contienen muchos minerales.'),
	(377, 'Alimentos con Antioxidantes', 'Alimentos que contienen sustancias que protegen las células.'),
	(378, 'Alimentos con Omega 3', 'Alimentos que contienen ácidos grasos omega 3.'),
	(379, 'Alimentos con Calcio', 'Alimentos que contienen calcio.'),
	(380, 'Alimentos con Hierro', 'Alimentos que contienen hierro.'),
	(381, 'Alimentos con Potasio', 'Alimentos que contienen potasio.'),
	(382, 'Alimentos con Magnesio', 'Alimentos que contienen magnesio.'),
	(383, 'Alimentos con Zinc', 'Alimentos que contienen zinc.'),
	(384, 'Alimentos con Yodo', 'Alimentos que contienen yodo.'),
	(385, 'Alimentos con Selenio', 'Alimentos que contienen selenio.'),
	(386, 'Alimentos con Cobre', 'Alimentos que contienen cobre.'),
	(387, 'Alimentos con Manganeso', 'Alimentos que contienen manganeso.'),
	(388, 'Alimentos con Cromo', 'Alimentos que contienen cromo.'),
	(389, 'Alimentos con Molibdeno', 'Alimentos que contienen molibdeno.'),
	(390, 'Alimentos con Flúor', 'Alimentos que contienen flúor.'),
	(391, 'Alimentos con Cloro', 'Alimentos que contienen cloro.'),
	(392, 'Alimentos con Fósforo', 'Alimentos que contienen fósforo.'),
	(393, 'Alimentos con Azufre', 'Alimentos que contienen azufre.'),
	(394, 'Alimentos con Sodio', 'Alimentos que contienen sodio.'),
	(395, 'Alimentos con Cloruro', 'Alimentos que contienen cloruro.'),
	(396, 'Alimentos con Bicarbonato', 'Alimentos que contienen bicarbonato.'),
	(397, 'Alimentos con Amonio', 'Alimentos que contienen amonio.'),
	(398, 'Alimentos con Nitrato', 'Alimentos que contienen nitrato.'),
	(399, 'Alimentos con Nitrito', 'Alimentos que contienen nitrito.'),
	(400, 'Alimentos con Sulfato', 'Alimentos que contienen sulfato.'),
	(401, 'Alimentos con Carbonato', 'Alimentos que contienen carbonato.'),
	(402, 'Alimentos con Silicato', 'Alimentos que contienen silicato.'),
	(403, 'Alimentos con Borato', 'Alimentos que contienen borato.'),
	(404, 'Alimentos con Fluoruro', 'Alimentos que contienen fluoruro.'),
	(405, 'Alimentos con Bromuro', 'Alimentos que contienen bromuro.'),
	(406, 'Alimentos con Yoduro', 'Alimentos que contienen yoduro.'),
	(407, 'Alimentos con Cianuro', 'Alimentos que contienen cianuro.'),
	(408, 'Alimentos con Tiocianato', 'Alimentos que contienen tiocianato.'),
	(409, 'Alimentos con Oxalato', 'Alimentos que contienen oxalato.'),
	(410, 'Alimentos con Acetato', 'Alimentos que contienen acetato.'),
	(411, 'Alimentos con Propionato', 'Alimentos que contienen propionato.'),
	(412, 'Alimentos con Butirato', 'Alimentos que contienen butirato.'),
	(413, 'Alimentos con Valerato', 'Alimentos que contienen valerato.'),
	(414, 'Alimentos con Caproato', 'Alimentos que contienen caproato.'),
	(415, 'Alimentos con Enantato', 'Alimentos que contienen enantato.'),
	(416, 'Alimentos con Caprilato', 'Alimentos que contienen caprilato.'),
	(417, 'Alimentos con Pelargonato', 'Alimentos que contienen pelargonato.'),
	(418, 'Alimentos con Caprato', 'Alimentos que contienen caprato.'),
	(419, 'Alimentos con Undecilenato', 'Alimentos que contienen undecilenato.'),
	(420, 'Alimentos con Laurato', 'Alimentos que contienen laurato.'),
	(421, 'Alimentos con Miristato', 'Alimentos que contienen miristato.'),
	(422, 'Alimentos con Palmitato', 'Alimentos que contienen palmitato.'),
	(423, 'Alimentos con Estearato', 'Alimentos que contienen estearato.'),
	(424, 'Alimentos con Oleato', 'Alimentos que contienen oleato.'),
	(425, 'Alimentos con Linoleato', 'Alimentos que contienen linoleato.'),
	(426, 'Alimentos con Linolenato', 'Alimentos que contienen linolenato.'),
	(427, 'Alimentos con Araquidato', 'Alimentos que contienen araquidato.'),
	(428, 'Alimentos con Behenato', 'Alimentos que contienen behenato.'),
	(429, 'Alimentos con Lignocerato', 'Alimentos que contienen lignocerato.'),
	(430, 'Alimentos con Cerotato', 'Alimentos que contienen cerotato.'),
	(431, 'Alimentos con Melisato', 'Alimentos que contienen melisato.'),
	(432, 'Alimentos con Ácido Acético', 'Alimentos que contienen ácido acético.'),
	(433, 'Alimentos con Ácido Propiónico', 'Alimentos que contienen ácido propiónico.'),
	(434, 'Alimentos con Ácido Butírico', 'Alimentos que contienen ácido butírico.'),
	(435, 'Alimentos con Ácido Valérico', 'Alimentos que contienen ácido valérico.'),
	(436, 'Alimentos con Ácido Caproico', 'Alimentos que contienen ácido caproico.'),
	(437, 'Alimentos con Ácido Enántico', 'Alimentos que contienen ácido enántico.'),
	(438, 'Alimentos con Ácido Caprílico', 'Alimentos que contienen ácido caprílico.'),
	(439, 'Alimentos con Ácido Pelargónico', 'Alimentos que contienen ácido pelargónico.'),
	(440, 'Alimentos con Ácido Cáprico', 'Alimentos que contienen ácido cáprico.'),
	(441, 'Alimentos con Ácido Undecílico', 'Alimentos que contienen ácido undecílico.'),
	(442, 'Alimentos con Ácido Láurico', 'Alimentos que contienen ácido láurico.'),
	(443, 'Alimentos con Ácido Mirístico', 'Alimentos que contienen ácido mirístico.'),
	(444, 'Alimentos con Ácido Palmítico', 'Alimentos que contienen ácido palmítico.'),
	(445, 'Alimentos con Ácido Esteárico', 'Alimentos que contienen ácido esteárico.'),
	(446, 'Alimentos con Ácido Oleico', 'Alimentos que contienen ácido oleico.'),
	(447, 'Alimentos con Ácido Linoleico', 'Alimentos que contienen ácido linoleico.'),
	(448, 'Alimentos con Ácido Linolénico', 'Alimentos que contienen ácido linolénico.'),
	(449, 'Alimentos con Ácido Araquídico', 'Alimentos que contienen ácido araquídico.'),
	(450, 'Alimentos con Ácido Behénico', 'Alimentos que contienen ácido behénico.'),
	(451, 'Alimentos con Ácido Lignocérico', 'Alimentos que contienen ácido lignocérico.'),
	(452, 'Alimentos con Ácido Cerótico', 'Alimentos que contienen ácido cerótico.'),
	(453, 'Alimentos con Ácido Melísico', 'Alimentos que contienen ácido melísico.'),
	(454, 'Alimentos con Ácido Nervónico', 'Alimentos que contienen ácido nervónico.'),
	(455, 'Alimentos con Ácido Gadoleico', 'Alimentos que contienen ácido gadoleico.'),
	(456, 'Alimentos con Ácido Eicosapentaenoico (EPA)', 'Alimentos que contienen ácido eicosapentaenoico (EPA).'),
	(457, 'Alimentos con Ácido Docosahexaenoico (DHA)', 'Alimentos que contienen ácido docosahexaenoico (DHA).'),
	(458, 'Alimentos con Ácido Araquidónico', 'Alimentos que contienen ácido araquidónico.'),
	(459, 'Alimentos con Ácido Docosapentaenoico (DPA)', 'Alimentos que contienen ácido docosapentaenoico (DPA).'),
	(460, 'Alimentos con Ácido Clupanodónico', 'Alimentos que contienen ácido clupanodónico.'),
	(461, 'Alimentos con Ácido Tetracosapentaenoico', 'Alimentos que contienen ácido tetracosapentaenoico.');

-- Volcando estructura para tabla pp3_proyecto.clientes
CREATE TABLE IF NOT EXISTS `clientes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  `apellido` varchar(255) DEFAULT NULL,
  `direccion` varchar(255) DEFAULT NULL,
  `telefono` varchar(50) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `fecha_registro` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Volcando datos para la tabla pp3_proyecto.clientes: ~0 rows (aproximadamente)

-- Volcando estructura para tabla pp3_proyecto.compras
CREATE TABLE IF NOT EXISTS `compras` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `proveedor_id` int(11) NOT NULL,
  `fecha_compra` timestamp NULL DEFAULT current_timestamp(),
  `total_compra` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_compras_proveedores` (`proveedor_id`),
  CONSTRAINT `fk_compras_proveedores` FOREIGN KEY (`proveedor_id`) REFERENCES `proveedores` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Volcando datos para la tabla pp3_proyecto.compras: ~0 rows (aproximadamente)

-- Volcando estructura para tabla pp3_proyecto.detallescompra
CREATE TABLE IF NOT EXISTS `detallescompra` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `compra_id` int(11) NOT NULL,
  `producto_id` int(11) NOT NULL,
  `cantidad` int(11) NOT NULL,
  `precio_unitario_compra` decimal(10,2) NOT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_detallescompra_compra` (`compra_id`),
  KEY `fk_detallescompra_producto` (`producto_id`),
  CONSTRAINT `fk_detallescompra_compra` FOREIGN KEY (`compra_id`) REFERENCES `compras` (`id`),
  CONSTRAINT `fk_detallescompra_producto` FOREIGN KEY (`producto_id`) REFERENCES `productos` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Volcando datos para la tabla pp3_proyecto.detallescompra: ~0 rows (aproximadamente)

-- Volcando estructura para tabla pp3_proyecto.detallesventa
CREATE TABLE IF NOT EXISTS `detallesventa` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `venta_id` int(11) NOT NULL,
  `producto_id` int(11) NOT NULL,
  `cantidad` int(11) NOT NULL,
  `precio_unitario_venta` decimal(10,2) NOT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_detallesventa_venta` (`venta_id`),
  KEY `fk_detallesventa_producto` (`producto_id`),
  CONSTRAINT `fk_detallesventa_producto` FOREIGN KEY (`producto_id`) REFERENCES `productos` (`id`),
  CONSTRAINT `fk_detallesventa_venta` FOREIGN KEY (`venta_id`) REFERENCES `ventas` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Volcando datos para la tabla pp3_proyecto.detallesventa: ~0 rows (aproximadamente)

-- Volcando estructura para procedimiento pp3_proyecto.insertar_categorias
DELIMITER //
CREATE PROCEDURE `insertar_categorias`()
BEGIN
  DECLARE i INT DEFAULT 1;
  WHILE i <= 10000 DO
    INSERT INTO Categorias (nombre, descripcion)
    VALUES (
      CONCAT('Categoria ', LPAD(i, 5, '0')),
      CONCAT('Descripción de la categoría ', i)
    );
    SET i = i + 1;
  END WHILE;
END//
DELIMITER ;

-- Volcando estructura para procedimiento pp3_proyecto.insertar_marcas
DELIMITER //
CREATE PROCEDURE `insertar_marcas`()
BEGIN
  DECLARE i INT DEFAULT 1;
  WHILE i <= 10000 DO
    INSERT INTO Marcas (nombre)
    VALUES (CONCAT('Marca ', LPAD(i, 5, '0')));
    SET i = i + 1;
  END WHILE;
END//
DELIMITER ;

-- Volcando estructura para procedimiento pp3_proyecto.insertar_productos
DELIMITER //
CREATE PROCEDURE `insertar_productos`()
BEGIN
  DECLARE i INT DEFAULT 1;
  WHILE i <= 10000 DO
    INSERT INTO Productos (
      nombre, descripcion, precio_costo, precio_venta,
      stock, marca_id, categoria_id, codigo_barras
    ) VALUES (
      CONCAT('Producto ', LPAD(i, 5, '0')),
      CONCAT('Descripción del producto ', i),
      ROUND(10 + (RAND() * 90), 2),
      ROUND(100 + (RAND() * 400), 2),
      FLOOR(1 + RAND() * 100),
      FLOOR(1 + RAND() * 10000),
      FLOOR(1 + RAND() * 10000),
      CONCAT('CB', LPAD(i, 10, '0'))
    );
    SET i = i + 1;
  END WHILE;
END//
DELIMITER ;

-- Volcando estructura para tabla pp3_proyecto.marcas
CREATE TABLE IF NOT EXISTS `marcas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `nombre` (`nombre`)
) ENGINE=InnoDB AUTO_INCREMENT=207 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Volcando datos para la tabla pp3_proyecto.marcas: ~206 rows (aproximadamente)
INSERT IGNORE INTO `marcas` (`id`, `nombre`) VALUES
	(78, '9 de Oro'),
	(117, '9 de Oro (Bizcochos)'),
	(143, 'Activia'),
	(162, 'Aguila'),
	(157, 'Alfajor Capitán del Espacio'),
	(22, 'Alicante'),
	(39, 'Amanda'),
	(158, 'Amargo Obrero'),
	(60, 'Andes Origen'),
	(1, 'Arcor'),
	(89, 'Arcor (Chocolate)'),
	(11, 'Arcor (Frutas)'),
	(12, 'Arcor (Verduras)'),
	(37, 'Arlistán'),
	(135, 'Arlistán (Té)'),
	(2, 'Bagley'),
	(165, 'Bagley (Opera)'),
	(123, 'Bariloche'),
	(77, 'BC'),
	(27, 'Bon o Bon'),
	(163, 'Bonafide'),
	(59, 'Brahma'),
	(66, 'Budweiser'),
	(113, 'Cabaña Las Lilas'),
	(30, 'Cabrales'),
	(92, 'Cadbury'),
	(160, 'Café La Virginia'),
	(111, 'Cagnoli'),
	(68, 'Campari'),
	(112, 'Campo Austral'),
	(88, 'Canale'),
	(42, 'Carrefour'),
	(169, 'Casanto'),
	(51, 'Catena Zapata'),
	(138, 'CBSé'),
	(74, 'Cepita'),
	(41, 'Chamana'),
	(54, 'Chandon'),
	(28, 'Chocolinas'),
	(82, 'Cimes'),
	(166, 'Cindor'),
	(76, 'Clight'),
	(15, 'Coca-Cola Argentina'),
	(23, 'Cocinero'),
	(62, 'Corona'),
	(43, 'Coto'),
	(19, 'Cresta Roja'),
	(38, 'Cruz de Malta'),
	(134, 'Cruz del Sur'),
	(144, 'Danette'),
	(94, 'Danone'),
	(47, 'Dia'),
	(45, 'Disco'),
	(109, 'Don Felipe'),
	(79, 'Don Satur'),
	(146, 'Don Satur (Grasitas)'),
	(56, 'Estancia Mendoza'),
	(107, 'Express'),
	(50, 'Familia Zuccardi'),
	(127, 'Fanacoa'),
	(105, 'Fantoche'),
	(87, 'Favorita'),
	(164, 'Felfort'),
	(67, 'Fernet Branca'),
	(150, 'Freddo'),
	(18, 'Friar'),
	(29, 'Frigor'),
	(114, 'Frigorífico Rioplatense'),
	(99, 'Gallo'),
	(69, 'Gancia'),
	(120, 'Gentile'),
	(90, 'Georgalos'),
	(104, 'Godet'),
	(9, 'Granja Tres Arroyos'),
	(152, 'Grido'),
	(148, 'Havanna'),
	(63, 'Heineken'),
	(21, 'Hellmanns'),
	(159, 'Hesperidina'),
	(34, 'Ilolay'),
	(64, 'Imperial'),
	(115, 'Inalpa'),
	(106, 'Jorgito'),
	(46, 'Jumbo'),
	(96, 'Knorr'),
	(110, 'La Anónima'),
	(133, 'La Blanca'),
	(24, 'La Campagnola'),
	(122, 'La Cumbrecita'),
	(131, 'La Parmesana'),
	(36, 'La Paulina'),
	(20, 'La Salteña'),
	(3, 'La Serenísima'),
	(139, 'La Virginia'),
	(25, 'Lay\'s Argentina'),
	(103, 'Ledesma'),
	(129, 'Legítimo'),
	(71, 'Levité'),
	(172, 'Lightolait'),
	(102, 'Lucchetti'),
	(98, 'Lucchetti (Arroz)'),
	(13, 'Lucchetti (Legumbres)'),
	(5, 'Luchetti'),
	(97, 'Maggi'),
	(125, 'Mamá Cocina'),
	(80, 'Manaos'),
	(153, 'Mantecol'),
	(32, 'Marolio'),
	(86, 'Matarazzo'),
	(108, 'Media Noche'),
	(171, 'Mendicrim'),
	(35, 'Milkaut'),
	(65, 'Miller'),
	(116, 'Molinos Cañuelas'),
	(6, 'Molinos Río de la Plata'),
	(100, 'Molto'),
	(48, 'Natura'),
	(55, 'Navarro Correas'),
	(140, 'Nesquik'),
	(93, 'Nestlé (Argentina)'),
	(136, 'Nobleza Gaucha'),
	(7, 'Noel'),
	(121, 'Noel (Dulce de Leche)'),
	(52, 'Norton'),
	(154, 'Nucrem'),
	(49, 'Olivos del Salar'),
	(10, 'Paladini'),
	(4, 'Patagonia'),
	(84, 'Paty'),
	(118, 'Pepa'),
	(26, 'Pepitos'),
	(101, 'Pepsico'),
	(151, 'Persicco'),
	(137, 'Playadito'),
	(147, 'Postre Balcarce'),
	(126, 'Presto Pronta'),
	(81, 'Pritty'),
	(85, 'Quickfood'),
	(142, 'Quicky'),
	(58, 'Quilmes'),
	(149, 'Rapanui'),
	(156, 'Rodhesia'),
	(40, 'Rosamonte'),
	(83, 'Sadia'),
	(132, 'Salsati'),
	(57, 'Salta'),
	(53, 'San Huberto'),
	(33, 'Sancor'),
	(196, 'Sancor Azul'),
	(174, 'Sancor Bebé'),
	(188, 'Sancor Cheddar'),
	(182, 'Sancor Crema'),
	(185, 'Sancor Cremosísimo'),
	(200, 'Sancor Criollo'),
	(201, 'Sancor Danbo'),
	(179, 'Sancor Dulce de Leche'),
	(202, 'Sancor Edam'),
	(205, 'Sancor Emmental'),
	(178, 'Sancor Flan'),
	(197, 'Sancor Fontina'),
	(203, 'Sancor Gouda'),
	(195, 'Sancor Goya'),
	(204, 'Sancor Gruyere'),
	(190, 'Sancor Holanda'),
	(183, 'Sancor Manteca'),
	(181, 'Sancor Mendicream'),
	(189, 'Sancor Pategrás'),
	(199, 'Sancor Por Salut'),
	(177, 'Sancor Postres'),
	(194, 'Sancor Provolone'),
	(180, 'Sancor Queso Crema'),
	(206, 'Sancor Raclette'),
	(192, 'Sancor Reggianito'),
	(184, 'Sancor Ricotta'),
	(191, 'Sancor Romanito'),
	(186, 'Sancor Sancorito'),
	(193, 'Sancor Sardo'),
	(176, 'Sancor Shakes'),
	(187, 'Sancor Sublime'),
	(198, 'Sancor Tybo'),
	(175, 'Sancor Yogs'),
	(128, 'Savora'),
	(73, 'Ser'),
	(170, 'Serecol'),
	(167, 'Serenito'),
	(119, 'Smams'),
	(61, 'Stella Artois'),
	(91, 'Suchard'),
	(8, 'Swift'),
	(75, 'Tang'),
	(31, 'Taragüi'),
	(161, 'Té Lipton'),
	(70, 'Terma'),
	(14, 'Terrabusi'),
	(155, 'Tita'),
	(141, 'Toddy'),
	(145, 'Tonadita'),
	(16, 'Trapiche'),
	(124, 'Tronador'),
	(95, 'Unilever'),
	(44, 'Vea'),
	(72, 'Villa del Sur'),
	(130, 'Vinagre Argentino'),
	(17, 'Yogurísimo'),
	(173, 'Yogurísimo (Firmeza)'),
	(168, 'Yogurísimo (Yogurtines)');

-- Volcando estructura para tabla pp3_proyecto.productoproveedor
CREATE TABLE IF NOT EXISTS `productoproveedor` (
  `proveedor_id` int(11) NOT NULL,
  `producto_id` int(11) NOT NULL,
  `precio_compra` decimal(10,2) DEFAULT NULL,
  `fecha_ultima_compra` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`proveedor_id`,`producto_id`),
  KEY `fk_productoproveedor_producto` (`producto_id`),
  CONSTRAINT `fk_productoproveedor_producto` FOREIGN KEY (`producto_id`) REFERENCES `productos` (`id`),
  CONSTRAINT `fk_productoproveedor_proveedor` FOREIGN KEY (`proveedor_id`) REFERENCES `proveedores` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Volcando datos para la tabla pp3_proyecto.productoproveedor: ~0 rows (aproximadamente)

-- Volcando estructura para tabla pp3_proyecto.productos
CREATE TABLE IF NOT EXISTS `productos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  `descripcion` text DEFAULT NULL,
  `precio_costo` decimal(10,2) NOT NULL,
  `precio_venta` decimal(10,2) NOT NULL,
  `stock` int(11) NOT NULL DEFAULT 0,
  `marca_id` int(11) DEFAULT NULL,
  `categoria_id` int(11) DEFAULT NULL,
  `codigo_barras` varchar(50) DEFAULT NULL,
  `fecha_alta` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `codigo_barras` (`codigo_barras`),
  KEY `fk_productos_marcas` (`marca_id`),
  KEY `fk_productos_categorias` (`categoria_id`),
  CONSTRAINT `fk_productos_categorias` FOREIGN KEY (`categoria_id`) REFERENCES `categorias` (`id`),
  CONSTRAINT `fk_productos_marcas` FOREIGN KEY (`marca_id`) REFERENCES `marcas` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=139 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Volcando datos para la tabla pp3_proyecto.productos: ~138 rows (aproximadamente)
INSERT IGNORE INTO `productos` (`id`, `nombre`, `descripcion`, `precio_costo`, `precio_venta`, `stock`, `marca_id`, `categoria_id`, `codigo_barras`, `fecha_alta`) VALUES
	(1, 'Fideos Spaghetti 500g', 'Fideos de sémola de trigo', 55.75, 120.50, 200, 5, 16, NULL, '2025-05-18 03:00:00'),
	(2, 'Galletitas de Agua 300g', 'Galletitas saladas', 30.20, 85.00, 150, 2, 4, NULL, '2025-05-18 03:00:00'),
	(3, 'Leche Entera 1L', 'Leche de vaca entera', 70.00, 150.00, 100, 3, 7, NULL, '2025-05-18 03:00:00'),
	(4, 'Cerveza Rubia Lata', 'Cerveza clara en lata', 45.50, 110.00, 300, 4, 6, NULL, '2025-05-18 03:00:00'),
	(5, 'Arroz Largo Fino 1kg', 'Arroz de grano largo fino', 60.00, 130.00, 250, 1, 14, NULL, '2025-05-18 03:00:00'),
	(6, 'Tomates Enlatados 400g', 'Tomates pelados en lata', 25.80, 60.00, 120, 7, 3, NULL, '2025-05-18 03:00:00'),
	(7, 'Carne Picada Especial 1kg', 'Carne vacuna picada magra', 220.00, 450.00, 50, 8, 8, NULL, '2025-05-18 03:00:00'),
	(8, 'Filet de Merluza Congelado', 'Filet de merluza sin piel', 180.00, 380.00, 80, 9, 2, NULL, '2025-05-18 03:00:00'),
	(9, 'Salchichas Viena 1kg', 'Salchichas tipo Viena', 95.00, 210.00, 90, 10, 10, NULL, '2025-05-18 03:00:00'),
	(10, 'Manzanas Rojas 1kg', 'Manzanas rojas frescas', 40.00, 90.00, 180, 11, 11, NULL, '2025-05-18 03:00:00'),
	(11, 'Zanahorias 1kg', 'Zanahorias frescas', 35.00, 75.00, 160, 12, 12, NULL, '2025-05-18 03:00:00'),
	(12, 'Lentejas Secas 500g', 'Lentejas secas a granel', 42.00, 95.00, 140, 13, 13, NULL, '2025-05-18 03:00:00'),
	(13, 'Pan Integral 500g', 'Pan elaborado con harina integral', 50.00, 110.00, 110, 14, 4, NULL, '2025-05-18 03:00:00'),
	(14, 'Gaseosa Cola 2.25L', 'Gaseosa sabor cola', 65.00, 140.00, 220, 15, 5, NULL, '2025-05-18 03:00:00'),
	(15, 'Vino Tinto Malbec', 'Vino tinto varietal Malbec', 150.00, 320.00, 60, 16, 6, NULL, '2025-05-18 03:00:00'),
	(16, 'Yogur Natural 1L', 'Yogur natural sin azúcar', 80.00, 170.00, 70, 17, 7, NULL, '2025-05-18 03:00:00'),
	(17, 'Bife de Chorizo 1kg', 'Bife de chorizo de novillo', 250.00, 520.00, 40, 18, 8, NULL, '2025-05-18 03:00:00'),
	(18, 'Pechugas de Pollo 1kg', 'Pechugas de pollo frescas', 120.00, 250.00, 130, 19, 9, NULL, '2025-05-18 03:00:00'),
	(19, 'Jamon Cocido 250g', 'Jamon cocido feteado', 60.00, 130.00, 100, 20, 10, NULL, '2025-05-18 03:00:00'),
	(20, 'Salsa de Tomate 500g', 'Salsa de tomate para pastas', 30.00, 70.00, 190, 21, 17, NULL, '2025-05-18 03:00:00'),
	(21, 'Oregano Seco 50g', 'Oregano seco en hojas', 20.00, 45.00, 170, 22, 18, NULL, '2025-05-18 03:00:00'),
	(22, 'Aceite de Girasol 1.5L', 'Aceite de girasol refinado', 90.00, 190.00, 80, 23, 19, NULL, '2025-05-18 03:00:00'),
	(23, 'Vinagre de Manzana 500ml', 'Vinagre de sidra de manzana', 40.00, 90.00, 150, 24, 20, NULL, '2025-05-18 03:00:00'),
	(24, 'Papas Fritas 150g', 'Papas fritas en bolsa', 45.00, 100.00, 210, 25, 22, NULL, '2025-05-18 03:00:00'),
	(25, 'Alfajores de Maicena', 'Alfajores rellenos de dulce de leche', 75.00, 160.00, 90, 26, 21, NULL, '2025-05-18 03:00:00'),
	(26, 'Chocolate con Leche 100g', 'Chocolate con leche', 50.00, 110.00, 140, 27, 23, NULL, '2025-05-18 03:00:00'),
	(27, 'Flan Casero', 'Flan casero con dulce de leche', 60.00, 130.00, 120, 28, 24, NULL, '2025-05-18 03:00:00'),
	(28, 'Helado de Dulce de Leche 1kg', 'Helado sabor dulce de leche', 120.00, 250.00, 50, 29, 25, NULL, '2025-05-18 03:00:00'),
	(29, 'Cafe Molido 250g', 'Cafe molido tostado', 85.00, 180.00, 110, 30, 26, NULL, '2025-05-18 03:00:00'),
	(30, 'Te Negro 50 Saquitos', 'Te negro en saquitos', 35.00, 80.00, 160, 31, 27, NULL, '2025-05-18 03:00:00'),
	(31, 'Salsa Barbacoa 250g', 'Salsa barbacoa para carnes', 40.00, 90.00, 130, 32, 17, NULL, '2025-05-18 03:00:00'),
	(32, 'Yogur Bebible Frutilla', 'Yogur bebible sabor frutilla', 45.00, 100.00, 180, 33, 7, NULL, '2025-05-18 03:00:00'),
	(33, 'Queso Cremoso 500g', 'Queso cremoso en barra', 90.00, 200.00, 90, 34, 7, NULL, '2025-05-18 03:00:00'),
	(34, 'Manteca 200g', 'Manteca sin sal', 55.00, 120.00, 140, 35, 7, NULL, '2025-05-18 03:00:00'),
	(35, 'Te Verde 20 Saquitos', 'Te verde en saquitos', 30.00, 70.00, 170, 36, 27, NULL, '2025-05-18 03:00:00'),
	(36, 'Yerba Mate Suave 1kg', 'Yerba mate suave', 70.00, 150.00, 110, 37, 27, NULL, '2025-05-18 03:00:00'),
	(37, 'Hierbas Aromáticas Mix', 'Mix de hierbas aromáticas secas', 40.00, 90.00, 120, 38, 28, NULL, '2025-05-18 03:00:00'),
	(38, 'Fideos Tirabuzón 500g', 'Fideos tirabuzón de colores', 60.00, 130.00, 200, 39, 16, NULL, '2025-05-18 03:00:00'),
	(39, 'Gaseosa Lima-Limón 2.25L', 'Gaseosa sabor lima-limón', 65.00, 140.00, 210, 40, 5, NULL, '2025-05-18 03:00:00'),
	(40, 'Vino Blanco Chardonnay', 'Vino blanco varietal Chardonnay', 180.00, 380.00, 50, 41, 6, NULL, '2025-05-18 03:00:00'),
	(41, 'Dulce de Leche 500g', 'Dulce de leche repostero', 70.00, 150.00, 100, 42, 23, NULL, '2025-05-18 03:00:00'),
	(42, 'Aceitunas Verdes 300g', 'Aceitunas verdes en conserva', 45.00, 100.00, 160, 43, 1, NULL, '2025-05-18 03:00:00'),
	(43, 'Atun al Natural 170g', 'Atun al natural en lata', 55.00, 120.00, 130, 44, 3, NULL, '2025-05-18 03:00:00'),
	(44, 'Cacao en Polvo 200g', 'Cacao en polvo amargo', 40.00, 90.00, 190, 45, 23, NULL, '2025-05-18 03:00:00'),
	(45, 'Mermelada de Frutilla 450g', 'Mermelada de frutilla casera', 50.00, 110.00, 150, 46, 116, NULL, '2025-05-18 03:00:00'),
	(46, 'Nueces Peladas 100g', 'Nueces peladas sin sal', 60.00, 130.00, 120, 47, 117, NULL, '2025-05-18 03:00:00'),
	(47, 'Te de Manzanilla 20 Saquitos', 'Te de manzanilla en saquitos', 30.00, 70.00, 180, 48, 118, NULL, '2025-05-18 03:00:00'),
	(48, 'Aceite de Oliva 500ml', 'Aceite de oliva virgen extra', 120.00, 250.00, 80, 49, 119, NULL, '2025-05-18 03:00:00'),
	(49, 'Vinagre Balsamico 250ml', 'Vinagre balsamico italiano', 80.00, 170.00, 110, 50, 120, NULL, '2025-05-18 03:00:00'),
	(50, 'Mesa de Comedor Extensible', 'Mesa de comedor de madera', 5000.00, 10000.00, 5, 51, 121, NULL, '2025-05-18 03:00:00'),
	(51, 'Sillas de Comedor Tapizadas', 'Sillas de comedor con tela', 1500.00, 3000.00, 20, 52, 122, NULL, '2025-05-18 03:00:00'),
	(52, 'Sofa Cama 2 Cuerpos', 'Sofa que se convierte en cama', 8000.00, 16000.00, 10, 53, 123, NULL, '2025-05-18 03:00:00'),
	(53, 'Sillon Reclinable Cuero', 'Sillon individual reclinable', 6000.00, 12000.00, 15, 54, 124, NULL, '2025-05-18 03:00:00'),
	(54, 'Estanteria Modular Blanca', 'Estanteria con estantes movibles', 4000.00, 8000.00, 8, 55, 125, NULL, '2025-05-18 03:00:00'),
	(55, 'Cama Matrimonial con Almacenamiento', 'Cama con cajones inferiores', 12000.00, 24000.00, 3, 56, 126, NULL, '2025-05-18 03:00:00'),
	(56, 'Somier con Cajones Laterales', 'Base de cama con cajones', 9000.00, 18000.00, 7, 57, 127, NULL, '2025-05-18 03:00:00'),
	(57, 'Notebook Ultrabook 14"', 'Computadora portatil delgada', 70000.00, 140000.00, 12, 58, 128, NULL, '2025-05-18 03:00:00'),
	(58, 'Placa Base ATX Gaming', 'Placa madre para PC gamer', 15000.00, 30000.00, 25, 59, 129, NULL, '2025-05-18 03:00:00'),
	(59, 'Monitor Curvo 32"', 'Monitor de PC con pantalla curva', 45000.00, 90000.00, 10, 60, 130, NULL, '2025-05-18 03:00:00'),
	(60, 'Impresora Multifuncion Laser', 'Impresora que escanea y copia', 25000.00, 50000.00, 18, 61, 131, NULL, '2025-05-18 03:00:00'),
	(61, 'Teclado Mecanico RGB', 'Teclado para juegos con luces', 8000.00, 16000.00, 30, 62, 132, NULL, '2025-05-18 03:00:00'),
	(62, 'Auriculares Gaming Inalambricos', 'Auriculares con microfono para juegos', 12000.00, 24000.00, 22, 63, 133, NULL, '2025-05-18 03:00:00'),
	(63, 'Disco Solido SSD 1TB', 'Disco de estado solido interno', 18000.00, 36000.00, 20, 64, 134, NULL, '2025-05-18 03:00:00'),
	(64, 'Router Inalambrico Mesh', 'Router para conexion estable', 10000.00, 20000.00, 15, 65, 135, NULL, '2025-05-18 03:00:00'),
	(65, 'Tarjeta Grafica Nvidia RTX', 'Placa de video de alta gama', 80000.00, 160000.00, 8, 66, 136, NULL, '2025-05-18 03:00:00'),
	(66, 'Procesador Intel Core i9', 'Procesador de ultima generacion', 60000.00, 120000.00, 10, 67, 137, NULL, '2025-05-18 03:00:00'),
	(67, 'Memoria Ram DDR5 32GB', 'Modulo de memoria ram rapida', 20000.00, 40000.00, 28, 68, 138, NULL, '2025-05-18 03:00:00'),
	(68, 'Fuente Alimentacion 80 Plus', 'Fuente de poder eficiente', 12000.00, 24000.00, 16, 69, 139, NULL, '2025-05-18 03:00:00'),
	(69, 'Gabinete Pc Ventilacion', 'Caja para pc con buen flujo', 9000.00, 18000.00, 14, 70, 140, NULL, '2025-05-18 03:00:00'),
	(70, 'Refrigeracion Liquida Pc', 'Enfriador de agua para cpu', 15000.00, 30000.00, 11, 71, 141, NULL, '2025-05-18 03:00:00'),
	(71, 'Fideos Tirabuzón Sin Gluten 500g', 'Fideos de maíz y arroz, sin TACC', 70.00, 150.00, 180, 5, 142, NULL, '2025-05-18 03:00:00'),
	(72, 'Pan de Campo Kosher', 'Pan rústico elaborado bajo normas Kosher', 55.00, 120.00, 120, 14, 143, NULL, '2025-05-18 03:00:00'),
	(73, 'Salchichas de Pollo Halal 1kg', 'Salchichas de pollo procesadas según normas Halal', 100.00, 220.00, 90, 10, 144, NULL, '2025-05-18 03:00:00'),
	(74, 'Proteína Whey Vainilla 900g', 'Suplemento de proteína de suero de leche sabor vainilla', 350.00, 750.00, 60, 80, 145, NULL, '2025-05-18 03:00:00'),
	(75, 'Bebida Energética Guaraná 250ml', 'Bebida energizante con extracto de guaraná', 40.00, 90.00, 200, 5, 146, NULL, '2025-05-18 03:00:00'),
	(76, 'Jugo de Naranja Natural 1L', 'Jugo exprimido de naranjas frescas', 75.00, 160.00, 100, 15, 147, NULL, '2025-05-18 03:00:00'),
	(77, 'Agua Saborizada Manzana 500ml', 'Agua con saborizante natural de manzana', 30.00, 65.00, 150, 40, 148, NULL, '2025-05-18 03:00:00'),
	(78, 'Té Verde Frío Limón 1.5L', 'Té verde frío con sabor a limón', 50.00, 110.00, 130, 31, 149, NULL, '2025-05-18 03:00:00'),
	(79, 'Infusión Digestiva Menta y Jengibre', 'Infusión para después de las comidas', 45.00, 100.00, 110, 38, 150, NULL, '2025-05-18 03:00:00'),
	(80, 'Sillón de Cuero Clásico 3 Cuerpos', 'Sillón de cuero genuino estilo Chesterfield', 15000.00, 32000.00, 5, 54, 151, NULL, '2025-05-18 03:00:00'),
	(81, 'Mesa de Comedor Moderna Vidrio y Acero', 'Mesa con tapa de vidrio y patas de acero', 8000.00, 17000.00, 8, 51, 152, NULL, '2025-05-18 03:00:00'),
	(82, 'Cama Matrimonial Rústica Madera Maciza', 'Cama de madera maciza con diseño rústico', 12000.00, 25000.00, 3, 57, 153, NULL, '2025-05-18 03:00:00'),
	(83, 'Mesa de Oficina Vintage Escritorio', 'Mesa de madera con cajones estilo vintage', 6000.00, 13000.00, 10, 66, 154, NULL, '2025-05-18 03:00:00'),
	(84, 'Sillas de Jardín Plegables Metal y Madera', 'Set de sillas plegables para exterior', 4000.00, 8500.00, 15, 72, 155, NULL, '2025-05-18 03:00:00'),
	(85, 'Cama con Dosel Blanca', 'Cama con estructura para cortinas', 14000.00, 29000.00, 4, 57, 156, NULL, '2025-05-18 03:00:00'),
	(86, 'Somier Articulado Eléctrico', 'Somier con posiciones ajustables', 18000.00, 38000.00, 2, 93, 157, NULL, '2025-05-18 03:00:00'),
	(87, 'Notebook 2 en 1 Táctil 13"', 'Notebook convertible con pantalla táctil', 80000.00, 160000.00, 10, 97, 158, NULL, '2025-05-18 03:00:00'),
	(88, 'Mini PC Señalización Digital HDMI', 'Mini PC para pantallas publicitarias', 20000.00, 42000.00, 12, 99, 159, NULL, '2025-05-18 03:00:00'),
	(89, 'Servidor Blade 8 Nodos', 'Servidor compacto para centros de datos', 150000.00, 300000.00, 1, 100, 160, NULL, '2025-05-18 03:00:00'),
	(90, 'Pan de Masa Madre Centeno 500g', 'Pan artesanal de centeno con masa madre', 60.00, 130.00, 110, 111, 161, NULL, '2025-05-18 03:00:00'),
	(91, 'Queso Vegano Cheddar 200g', 'Queso vegetal tipo cheddar', 80.00, 170.00, 80, 112, 162, NULL, '2025-05-18 03:00:00'),
	(92, 'Chocolate 70% Cacao Sin Azúcar', 'Chocolate amargo sin azúcar añadida', 55.00, 120.00, 130, 113, 163, NULL, '2025-05-18 03:00:00'),
	(93, 'Bife de Chorizo Orgánico 1kg', 'Bife de chorizo de carne orgánica', 280.00, 580.00, 40, 114, 164, NULL, '2025-05-18 03:00:00'),
	(94, 'Cerveza Artesanal Trigo Botella', 'Cerveza de trigo estilo Weissbier', 45.00, 100.00, 150, 115, 165, NULL, '2025-05-18 03:00:00'),
	(95, 'Mermelada de Frambuesa Sin Azúcar', 'Mermelada de frambuesa sin azúcar agregada', 50.00, 110.00, 120, 116, 166, NULL, '2025-05-18 03:00:00'),
	(96, 'Almendras Tostadas Orgánicas 250g', 'Almendras tostadas sin sal', 70.00, 150.00, 90, 117, 167, NULL, '2025-05-18 03:00:00'),
	(97, 'Té de Frutas del Bosque 50g', 'Té con trozos de frutos rojos', 35.00, 80.00, 140, 118, 168, NULL, '2025-05-18 03:00:00'),
	(98, 'Aceite de Coco Virgen Extra 500ml', 'Aceite de coco para cocinar y uso cosmético', 90.00, 190.00, 100, 119, 169, NULL, '2025-05-18 03:00:00'),
	(99, 'Vinagre de Manzana Orgánico 250ml', 'Vinagre de manzana sin filtrar', 40.00, 90.00, 110, 120, 170, NULL, '2025-05-18 03:00:00'),
	(100, 'Mesa de Comedor Redonda Madera', 'Mesa redonda para 4 personas', 7500.00, 16000.00, 6, 121, 171, NULL, '2025-05-18 03:00:00'),
	(101, 'Sillas de Comedor Diseño Eames', 'Sillas modernas con patas de madera', 2000.00, 4200.00, 24, 122, 172, NULL, '2025-05-18 03:00:00'),
	(102, 'Sofá Modular 5 Piezas Gris', 'Sofá que se arma en varias configuraciones', 18000.00, 38000.00, 3, 173, 173, NULL, '2025-05-18 03:00:00'),
	(103, 'Sillón Masajeador Eléctrico', 'Sillón reclinable con función de masaje', 12000.00, 25000.00, 7, 174, 174, NULL, '2025-05-18 03:00:00'),
	(104, 'Estantería Flotante Cubos Blanca', 'Estantería para pared con cubos', 3500.00, 7500.00, 15, 175, 175, NULL, '2025-05-18 03:00:00'),
	(105, 'Cama con Cabecero Acolchado Pana', 'Cama con cabecero suave de pana', 13000.00, 27000.00, 5, 176, 176, NULL, '2025-05-18 03:00:00'),
	(106, 'Somier Eléctrico con Masaje', 'Somier con ajuste eléctrico y vibración', 22000.00, 45000.00, 2, 177, 177, NULL, '2025-05-18 03:00:00'),
	(107, 'Notebook Ultrabook OLED 15"', 'Notebook con pantalla OLED de alta calidad', 95000.00, 190000.00, 8, 128, 178, NULL, '2025-05-18 03:00:00'),
	(108, 'Placa Base Micro ATX AM4', 'Placa base compacta para procesadores AMD', 12000.00, 25000.00, 20, 179, 179, NULL, '2025-05-18 03:00:00'),
	(109, 'Monitor Ultrawide 144Hz FreeSync', 'Monitor panorámico para juegos', 55000.00, 110000.00, 9, 180, 180, NULL, '2025-05-18 03:00:00'),
	(110, 'Impresora Láser Color Multifunción WiFi', 'Impresora láser a color con WiFi', 35000.00, 72000.00, 11, 131, 181, NULL, '2025-05-18 03:00:00'),
	(111, 'Teclado Inalámbrico Ergonómico Split', 'Teclado dividido para mayor comodidad', 15000.00, 31000.00, 14, 182, 182, NULL, '2025-05-18 03:00:00'),
	(112, 'Auriculares Inalámbricos Noise Cancelling', 'Auriculares con cancelación de ruido', 20000.00, 42000.00, 12, 183, 183, NULL, '2025-05-18 03:00:00'),
	(113, 'Disco SSD Externo 1TB USB-C', 'Disco de estado sólido externo de alta velocidad', 25000.00, 52000.00, 10, 184, 184, NULL, '2025-05-18 03:00:00'),
	(114, 'Router Mesh WiFi 6 AX3000', 'Sistema de router para cobertura total', 18000.00, 38000.00, 7, 185, 185, NULL, '2025-05-18 03:00:00'),
	(115, 'Tarjeta Gráfica Radeon RX 6700 XT', 'Tarjeta de video AMD para juegos', 70000.00, 140000.00, 5, 186, 186, NULL, '2025-05-18 03:00:00'),
	(116, 'Procesador Ryzen 7 5800X', 'Procesador de 8 núcleos para PC', 60000.00, 120000.00, 8, 187, 187, NULL, '2025-05-18 03:00:00'),
	(117, 'Memoria RAM DDR4 3200MHz 64GB ECC', 'Memoria RAM con corrección de errores', 28000.00, 58000.00, 6, 188, 188, NULL, '2025-05-18 03:00:00'),
	(118, 'Fuente de Alimentación 850W 80+ Titanium', 'Fuente de alta eficiencia', 16000.00, 33000.00, 9, 189, 189, NULL, '2025-05-18 03:00:00'),
	(119, 'Gabinete PC Vidrio Templado RGB', 'Gabinete con luces y ventana', 13000.00, 27000.00, 11, 190, 190, NULL, '2025-05-18 03:00:00'),
	(120, 'Refrigeración Líquida AIO 240mm', 'Enfriador de agua para CPU', 19000.00, 40000.00, 10, 191, 191, NULL, '2025-05-18 03:00:00'),
	(121, 'Alimento para Cachorros Razas Pequeñas', 'Comida para cachorros de razas pequeñas', 80.00, 170.00, 120, 360, 192, NULL, '2025-05-18 03:00:00'),
	(122, 'Alimento para Gatos Adultos Salmón', 'Comida para gatos con sabor a salmón', 75.00, 160.00, 110, 361, 193, NULL, '2025-05-18 03:00:00'),
	(123, 'Barra de Proteína Vegana Chocolate', 'Barra energética con proteína vegetal', 45.00, 100.00, 150, 145, 194, NULL, '2025-05-18 03:00:00'),
	(124, 'Cereal Integral Enriquecido con Hierro', 'Cereal de desayuno con hierro añadido', 55.00, 120.00, 130, 14, 195, NULL, '2025-05-18 03:00:00'),
	(125, 'Leche de Almendras Fortificada con Calcio', 'Bebida vegetal con calcio y vitaminas', 60.00, 130.00, 100, 3, 196, NULL, '2025-05-18 03:00:00'),
	(126, 'Yogur Probiótico Natural Sin Azúcar', 'Yogur con bacterias beneficiosas', 70.00, 150.00, 90, 17, 197, NULL, '2025-05-18 03:00:00'),
	(127, 'Avena Prebiótica con Frutas Deshidratadas', 'Avena con fibra y frutas', 50.00, 110.00, 140, 14, 198, NULL, '2025-05-18 03:00:00'),
	(128, 'Batido Simbiótico de Frutas y Verduras', 'Bebida con probióticos y prebióticos', 80.00, 170.00, 80, 147, 199, NULL, '2025-05-18 03:00:00'),
	(129, 'Tomates Cherry Transgénicos Larga Duración', 'Tomates modificados para mayor vida útil', 40.00, 90.00, 160, 11, 200, NULL, '2025-05-18 03:00:00'),
	(130, 'Manzanas Orgánicas Granny Smith 1kg', 'Manzanas cultivadas sin químicos', 45.00, 100.00, 150, 11, 201, NULL, '2025-05-18 03:00:00'),
	(131, 'Leche Biológica Entera 1L', 'Leche de vaca de producción ecológica', 75.00, 160.00, 110, 3, 202, NULL, '2025-05-18 03:00:00'),
	(132, 'Miel Biodinámica de Flores Silvestres', 'Miel de abejas criadas en granja biodinámica', 90.00, 190.00, 100, 23, 203, NULL, '2025-05-18 03:00:00'),
	(133, 'Café de Comercio Justo Colombia 500g', 'Café en grano de origen ético', 85.00, 180.00, 90, 30, 204, NULL, '2025-05-18 03:00:00'),
	(134, 'Fresas de Temporada 1kg', 'Fresas frescas de cosecha local', 50.00, 110.00, 140, 11, 205, NULL, '2025-05-18 03:00:00'),
	(135, 'Zanahorias de Proximidad 1kg', 'Zanahorias de cultivo regional', 40.00, 90.00, 150, 12, 206, NULL, '2025-05-18 03:00:00'),
	(136, 'Pan Artesanal de Centeno y Espelta', 'Pan hecho a mano con harinas mixtas', 65.00, 140.00, 120, 111, 207, NULL, '2025-05-18 03:00:00'),
	(137, 'Queso de Cabra Gourmet Trufado', 'Queso de cabra con aroma a trufa', 120.00, 250.00, 50, 112, 208, NULL, '2025-05-18 03:00:00'),
	(138, 'Curry en Polvo Étnico Madras', 'Mezcla de especias para cocina india', 45.00, 100.00, 130, 22, 209, NULL, '2025-05-18 03:00:00');

-- Volcando estructura para tabla pp3_proyecto.proveedores
CREATE TABLE IF NOT EXISTS `proveedores` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  `contacto` varchar(255) DEFAULT NULL,
  `telefono` varchar(50) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `direccion` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Volcando datos para la tabla pp3_proyecto.proveedores: ~0 rows (aproximadamente)

-- Volcando estructura para tabla pp3_proyecto.ventas
CREATE TABLE IF NOT EXISTS `ventas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` int(11) DEFAULT NULL,
  `fecha_venta` timestamp NULL DEFAULT current_timestamp(),
  `total_venta` decimal(10,2) NOT NULL,
  `metodo_pago` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_ventas_clientes` (`cliente_id`),
  CONSTRAINT `fk_ventas_clientes` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Volcando datos para la tabla pp3_proyecto.ventas: ~0 rows (aproximadamente)

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
